### ISSUE TITLE
Word usage?

### ISSUE THREAD

**Issue by 3TUSK** [HundunStar/AutoTransfer#4]
从mcbbs过来的...看上去还不错。
几个问题：
0.en_US去哪了？（Forge在缺失语言文件时默认会读取en_US.lang）（如果只是在mcbbs发布，当我没问）
1.orbit...这个“轨道”是指行星运行的轨道，跑某种载具的轨道是track或者rail...
2.有没有计划加跨世界的传输系统支持？
Thanks for your time to reply.

**Comment by kaaass** [comment]
@HundunStar 什么鬼啊！

~~虽然我不是策划，但我还是~~跑过来说一下。
0.语言文件什么的还没加2333因为mod刚起步。
1.orbit这属于typo，~~不要在意这些细节~~。
2.似乎没有，不过既然你提醒我们了，可以要开个issue讨论下啊。

另：你是美工还是程序员？

**Comment by 3TUSK** [comment]
半职业mod汉化人员兼业余程序员，学生党，时间不多，美工苦手。

**Comment by HundunStar** [comment]
那先加群吧，群号：317205878
另：我是本mod总负责人兼创始人兼程序员兼美工（不要在意这些细节）

**Comment by 3TUSK** [comment]
我还是不要加了好...我是个经常潜水的人（喷）

**Comment by HundunStar** [comment]
一周做一次就行，你先加吧

**Comment by HundunStar** [comment]
看你出谋划策还是不错的QAQ

**Comment by liach** [comment]
Why don't you make an organization to keep this mod?

**Comment by HundunStar** [comment]
有群组啊，但是你不加我怎么办
